### ISSUE TITLE
nodenv over nvmish?

### ISSUE THREAD

**Issue by hurrymaplelad** [goodeggs/homebrew-devops#1]
My zsh was starting slowly (1-3 seconds). Profiling implicated rvm, nvm, and nvmish.  rbenv and it's clone [nodenv](https://github.com/OiNutter/nodenv) claim to solve this problem. Nvmish's package.json engines detection is clutch, so I ported it to a [nodenv plugin](https://github.com/hurrymaplelad/nodenv-package-json-engine) complete with some `bats` tests cribbed from a [similar rbenv plugin](https://github.com/aripollak/rbenv-bundler-ruby-version).

Auto-install hasn't been ported yet, but nodenv implodes if you don't have the required version installed, and will install versions with `nodenv install <version>`.

I'll try it out for a bit.  Zsh startup times are much improved.

**Comment by bobzoller** [comment]
sounds awesome.  feel free to make any changes to move to nodenv when you
feel it's vetted.
